resolver: snapshot.yaml
packages:
  - ./persistent
  - ./persistent-template
#  - ./persistent-test
#  - ./persistent-mongoDB
#  - ./persistent-mysql
#  - ./persistent-postgresql
#  - ./persistent-redis
#  - ./persistent-qq
    #  - ./persistent-sqlite
    #  - ./persistent-test
    #  - ./persistent-mongoDB
    #  - ./persistent-mysql
    #  - ./persistent-postgresql
    #  - ./persistent-redis
    #  - ./persistent-qq
extra-deps:
